#!/bin/bash
#CUDA_PATH="/usr/local/cuda-12.1"
CUDA_PATH="/usr/local/cuda-11.4"
export CUDA_PATH=$CUDA_PATH
export CUDA_HOME=$CUDA_PATH
export CUDA_TOOLKIT_ROOT_DIR=$CUDA_PATH
export CMAKE_CUDA_COMPILER_TOOLKIT_ROOT=$CUDA_PATH
export PATH=$CUDA_PATH/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_PATH/lib64:$LD_LIBRARY_PATH

export CMAKE_CUDA_COMPILER=$CUDA_PATH/bin/nvcc

